### ISSUE TITLE
StringIndexOutOfBoundsException in dllearner

### ISSUE THREAD

**Issue by denkv** [dice-group/raki-ilp-benchmark#6]
```
2021-11-16T16:16:34.244Z 	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-11-16T16:16:34.244Z Concept: 
2021-11-16T16:16:34.243Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2021-11-16T16:16:34.243Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2021-11-16T16:16:34.242Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2021-11-16T16:16:34.242Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2021-11-16T16:16:34.241Z 	at org.dice_group.raki.hobbit.systems.DLLearnerSystemAdapter.createConcept(DLLearnerSystemAdapter.java:79) ~[systems.jar:?]
2021-11-16T16:16:34.241Z 	at org.dice_group.raki.hobbit.system.AbstractRakiSystemAdapter.lambda$receiveGeneratedTask$0(AbstractRakiSystemAdapter.java:113) ~[systems.jar:?]
2021-11-16T16:16:34.240Z 	at org.dice_group.raki.hobbit.systems.DLLearnerSystemAdapter.celeo(DLLearnerSystemAdapter.java:105) ~[systems.jar:?]
2021-11-16T16:16:34.240Z 	at org.dllearner.algorithms.celoe.CELOE.getNextNodeToExpand(CELOE.java:476) ~[systems.jar:?]
2021-11-16T16:16:34.240Z 	at org.dllearner.algorithms.celoe.CELOE.start(CELOE.java:337) ~[systems.jar:?]
2021-11-16T16:16:34.239Z 	at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
2021-11-16T16:16:34.239Z 	at java.lang.String.valueOf(String.java:2951) ~[?:?]
2021-11-16T16:16:34.238Z 	at org.dllearner.algorithms.celoe.OENode.getShortDescription(OENode.java:106) ~[systems.jar:?]
2021-11-16T16:16:34.238Z 	at org.dllearner.algorithms.celoe.OENode.toString(OENode.java:122) ~[systems.jar:?]
2021-11-16T16:16:34.237Z 	at org.dllearner.utilities.owl.OWLAPIRenderers.toDLSyntax(OWLAPIRenderers.java:58) ~[systems.jar:?]
2021-11-16T16:16:34.237Z 	at org.dllearner.algorithms.celoe.OENode.getShortDescription(OENode.java:110) ~[systems.jar:?]
2021-11-16T16:16:34.236Z 	at org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer.render(DLSyntaxObjectRenderer.java:80) ~[systems.jar:?]
2021-11-16T16:16:34.236Z 	at java.lang.StringBuilder.toString(StringBuilder.java:449) ~[?:?]
2021-11-16T16:16:34.235Z 	at java.lang.StringUTF16.compress(StringUTF16.java:169) ~[?:?]
2021-11-16T16:16:34.235Z 	at java.lang.StringUTF16.compress(StringUTF16.java:195) ~[?:?]
2021-11-16T16:16:34.235Z 	at java.lang.StringUTF16.newString(StringUTF16.java:1019) ~[?:?]
2021-11-16T16:16:34.234Z 	at java.lang.String.checkBoundsOffCount(String.java:3304) ~[?:?]
2021-11-16T16:16:34.234Z 	at java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1482) ~[?:?]
2021-11-16T16:16:34.233Z %d [%thread] %-5level %logger - %msg%n java.lang.StringIndexOutOfBoundsException: offset 0, count 35, length 34
2021-11-16T16:16:34.215Z Concept: 
2021-11-16T16:15:34.213Z Concept: 
2021-11-16T16:14:34.210Z Concept: 
2021-11-16T16:13:34.208Z Concept: 
2021-11-16T16:12:34.057Z Concept: carcinogenesis:Methyl
2021-11-16T16:11:34.032Z Concept: carcinogenesis:Nitrogen
2021-11-16T16:10:33.982Z Concept: carcinogenesis:Alcohol
2021-11-16T16:09:33.957Z Concept: carcinogenesis:Structure
2021-11-16T16:08:33.937Z Concept: carcinogenesis:Amino
2021-11-16T16:07:33.910Z Concept: carcinogenesis:Amine
2021-11-16T16:06:33.891Z Concept: carcinogenesis:Bond-2
2021-11-16T16:05:33.703Z Concept: carcinogenesis:Halide
2021-11-16T16:04:33.653Z 	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-11-16T16:04:33.653Z Concept: 
2021-11-16T16:04:33.652Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2021-11-16T16:04:33.651Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2021-11-16T16:04:33.651Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2021-11-16T16:04:33.650Z 	at org.dice_group.raki.hobbit.system.AbstractRakiSystemAdapter.lambda$receiveGeneratedTask$0(AbstractRakiSystemAdapter.java:113) ~[systems.jar:?]
2021-11-16T16:04:33.650Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
2021-11-16T16:04:33.649Z 	at org.dice_group.raki.hobbit.systems.DLLearnerSystemAdapter.celeo(DLLearnerSystemAdapter.java:105) ~[systems.jar:?]
2021-11-16T16:04:33.649Z 	at org.dice_group.raki.hobbit.systems.DLLearnerSystemAdapter.createConcept(DLLearnerSystemAdapter.java:79) ~[systems.jar:?]
2021-11-16T16:04:33.648Z 	at org.dllearner.algorithms.celoe.CELOE.getNextNodeToExpand(CELOE.java:476) ~[systems.jar:?]
2021-11-16T16:04:33.648Z 	at org.dllearner.algorithms.celoe.CELOE.start(CELOE.java:337) ~[systems.jar:?]
2021-11-16T16:04:33.647Z 	at java.lang.String.valueOf(String.java:2951) ~[?:?]
2021-11-16T16:04:33.647Z 	at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
2021-11-16T16:04:33.646Z 	at org.dllearner.algorithms.celoe.OENode.toString(OENode.java:122) ~[systems.jar:?]
2021-11-16T16:04:33.646Z 	at org.dllearner.algorithms.celoe.OENode.getShortDescription(OENode.java:106) ~[systems.jar:?]
2021-11-16T16:04:33.645Z 	at org.dllearner.algorithms.celoe.OENode.getShortDescription(OENode.java:110) ~[systems.jar:?]
2021-11-16T16:04:33.644Z 	at org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer.render(DLSyntaxObjectRenderer.java:79) ~[systems.jar:?]
2021-11-16T16:04:33.644Z 	at org.dllearner.utilities.owl.OWLAPIRenderers.toDLSyntax(OWLAPIRenderers.java:58) ~[systems.jar:?]
2021-11-16T16:04:33.643Z 	at uk.ac.manchester.cs.owl.owlapi.OWLClassImpl.accept(OWLClassImpl.java:245) ~[systems.jar:?]
2021-11-16T16:04:33.643Z 	at org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer.visit(DLSyntaxObjectRenderer.java:504) ~[systems.jar:?]
2021-11-16T16:04:33.642Z 	at org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer.writeEntity(DLSyntaxObjectRenderer.java:102) ~[systems.jar:?]
2021-11-16T16:04:33.641Z 	at org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer.write(DLSyntaxObjectRenderer.java:93) ~[systems.jar:?]
2021-11-16T16:04:33.640Z 	at java.lang.StringBuilder.append(StringBuilder.java:174) ~[?:?]
2021-11-16T16:04:33.639Z 	at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1667) ~[?:?]
2021-11-16T16:04:33.639Z 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539) ~[?:?]
2021-11-16T16:04:33.638Z 	at java.lang.String.getBytes(String.java:3194) ~[?:?]
2021-11-16T16:04:33.637Z 	at java.lang.StringLatin1.inflate(StringLatin1.java:734) ~[?:?]
2021-11-16T16:04:33.636Z 	at java.lang.StringUTF16.inflate(StringUTF16.java:1308) ~[?:?]
2021-11-16T16:04:33.635Z 	at java.lang.StringUTF16.checkBoundsOffCount(StringUTF16.java:1482) ~[?:?]
2021-11-16T16:04:33.634Z %d [%thread] %-5level %logger - %msg%n java.lang.StringIndexOutOfBoundsException: offset 8, count 14, length 17
2021-11-16T16:04:33.634Z 	at java.lang.String.checkBoundsOffCount(String.java:3304) ~[?:?]
2021-11-16T16:04:33.587Z Concept: 
2021-11-16T16:03:33.585Z Concept: 
2021-11-16T16:02:33.414Z Concept: carcinogenesis:Phenol
2021-11-16T16:01:33.384Z Concept: carcinogenesis:Bond-7
2021-11-16T16:00:33.184Z Concept: carcinogenesis:Sulfo
2021-11-16T15:59:33.158Z 
Concept: carcinogenesis:Non_ar_5c_ring
[====.] 99%
```

**Comment by SimonBin** [comment]
2021-11-16T16:04:33.641Z 	at org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxObjectRenderer.write(DLSyntaxObjectRenderer.java:93) ~[systems.jar:?]

--> should output something like 

⊤

∃ team_home.⊤

...

**Comment by denkv** [comment]
Turns out this is already ignored by our system adapter for HOBBIT. It just logs the exception. Unless we call dllearner in a wrong way, it's not a problem in `raki-ilp-benchmark`.
